version: '3'

services:
    php:
        container_name: php
        build:
            context: ./docker/php
        ports: 
            - '${PORT_PHP}:9000'
        volumes:
            - ./backend:/var/www/html
    mysql:
        image: mysql:8
        container_name: mysql
        ports:
            - "${PORT_MYSQL}:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USER}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
    nginx:
        image: nginx
        container_name: nginx
        ports:
            - "${PORT_HTTP}:80"
            - "${PORT_HTTPS}:443"
        volumes:
            - ./backend:/var/www/html
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        links:
            - php
    redis:
        image: redis
        container_name: redis
        ports:
            - "${REDIS_PORT}:6379"
        volumes:
            - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
            REDIS_HOST: '${REDIS_HOST}'
            REDIS_CLIENT: '${REDIS_CLIENT}'
            CACHE_DRIVER: '${CACHE_DRIVER}'